var sourcesIndex = JSON.parse('{\
"01_quick_derive":["",[],["01_quick.rs"]],\
"02_app_settings_derive":["",[],["02_app_settings.rs"]],\
"02_apps":["",[],["02_apps.rs"]],\
"02_apps_derive":["",[],["02_apps.rs"]],\
"02_crate_derive":["",[],["02_crate.rs"]],\
"03_01_flag_bool_derive":["",[],["03_01_flag_bool.rs"]],\
"03_01_flag_count_derive":["",[],["03_01_flag_count.rs"]],\
"03_02_option_derive":["",[],["03_02_option.rs"]],\
"03_02_option_mult_derive":["",[],["03_02_option_mult.rs"]],\
"03_03_positional_derive":["",[],["03_03_positional.rs"]],\
"03_03_positional_mult_derive":["",[],["03_03_positional_mult.rs"]],\
"03_04_subcommands_alt_derive":["",[],["03_04_subcommands_alt.rs"]],\
"03_04_subcommands_derive":["",[],["03_04_subcommands.rs"]],\
"03_05_default_values_derive":["",[],["03_05_default_values.rs"]],\
"04_01_enum_derive":["",[],["04_01_enum.rs"]],\
"04_02_parse_derive":["",[],["04_02_parse.rs"]],\
"04_02_validate_derive":["",[],["04_02_validate.rs"]],\
"04_03_relations_derive":["",[],["04_03_relations.rs"]],\
"04_04_custom_derive":["",[],["04_04_custom.rs"]],\
"05_01_assert_derive":["",[],["05_01_assert.rs"]],\
"busybox":["",[],["multicall-busybox.rs"]],\
"cargo_example_derive":["",[],["cargo-example-derive.rs"]],\
"clap":["",[["builder",[],["action.rs","app_settings.rs","arg.rs","arg_group.rs","arg_predicate.rs","arg_settings.rs","command.rs","debug_asserts.rs","mod.rs","os_str.rs","possible_value.rs","range.rs","resettable.rs","str.rs","styled_str.rs","value_hint.rs","value_parser.rs"]],["error",[],["context.rs","format.rs","kind.rs","mod.rs"]],["output",[["textwrap",[],["core.rs","mod.rs"]]],["fmt.rs","help.rs","help_template.rs","mod.rs","usage.rs"]],["parser",[["features",[],["mod.rs","suggestions.rs"]],["matches",[],["any_value.rs","arg_matches.rs","matched_arg.rs","mod.rs","value_source.rs"]]],["arg_matcher.rs","error.rs","mod.rs","parser.rs","validator.rs"]],["util",[],["color.rs","flat_map.rs","flat_set.rs","graph.rs","id.rs","mod.rs","str_to_bool.rs"]]],["derive.rs","lib.rs","macros.rs","mkeymap.rs"]],\
"clap_complete":["",[["generator",[],["mod.rs","utils.rs"]],["shells",[],["bash.rs","elvish.rs","fish.rs","mod.rs","powershell.rs","shell.rs","zsh.rs"]]],["lib.rs","macros.rs"]],\
"clap_complete_fig":["",[],["fig.rs","lib.rs"]],\
"clap_mangen":["",[],["lib.rs","render.rs"]],\
"completion":["",[],["completion.rs"]],\
"completion_derive":["",[],["completion-derive.rs"]],\
"demo":["",[],["demo.rs"]],\
"escaped_positional_derive":["",[],["escaped-positional-derive.rs"]],\
"fig_completion":["",[],["fig_completion.rs"]],\
"git":["",[],["git.rs"]],\
"git_derive":["",[],["git-derive.rs"]],\
"hostname":["",[],["multicall-hostname.rs"]],\
"interop_augment_args":["",[],["augment_args.rs"]],\
"interop_augment_subcommands":["",[],["augment_subcommands.rs"]],\
"interop_flatten_hand_args":["",[],["flatten_hand_args.rs"]],\
"interop_hand_subcommand":["",[],["hand_subcommand.rs"]],\
"man":["",[],["man.rs"]],\
"pacman":["",[],["pacman.rs"]],\
"repl":["",[],["repl.rs"]],\
"typed_derive":["",[],["typed-derive.rs"]]\
}');
createSourceSidebar();
